# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX1) += ex1/hello.o
obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX2) += ex2/oops.o
obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX3) += ex3/timer.o
obj-$(CONFIG_LKSS_DRIVERS_LAB1_EX4) += ex4/lkss_platform_driver.o
